# This Dockerfile assumes that the user has managed to natively mvn package the relevant files
FROM dsaidgovsg/spark-k8s-addons:v4_3.0.1_hadoop-3.2.0_scala-2.12_python-3.6 as pinot-ingest

ENV PINOT_VERSION="0.8.0"
ENV PINOT_HOME=/opt/pinot

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends vim wget curl git python && \
    rm -rf /var/lib/apt/lists/*

COPY pinot-distribution/target/apache-pinot-${PINOT_VERSION}-bin/apache-pinot-${PINOT_VERSION}-bin ${PINOT_HOME}
COPY pinot-plugins/pinot-batch-ingestion/pinot-batch-ingestion-spark/target/pinot-batch-ingestion-spark-${PINOT_VERSION}-shaded.jar ${PINOT_HOME}/lib/
COPY pinot-plugins/pinot-file-system/pinot-s3/target/pinot-s3-${PINOT_VERSION}-shaded.jar ${PINOT_HOME}/lib/
COPY pinot-plugins/pinot-input-format/pinot-parquet/target/pinot-parquet-${PINOT_VERSION}-shaded.jar ${PINOT_HOME}/lib/

WORKDIR ${PINOT_HOME}

RUN mkdir -p ${PINOT_HOME}/configs && \
    mkdir -p ${PINOT_HOME}/data && \
    chmod +x ${PINOT_HOME}/bin/*.sh

ENTRYPOINT ["./bin/pinot-admin.sh"]

CMD ["run"]
