# This Dockerfile assumes that the user has managed to natively mvn package the relevant files
FROM dsaidgovsg/spark-k8s-addons:v4_3.0.1_hadoop-3.2.0_scala-2.12_python-3.6 as pinot-ingest

ENV PINOT_VERSION="0.8.0"
ENV PINOT_HOME=/opt/pinot

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends vim wget curl git python && \
    rm -rf /var/lib/apt/lists/*

COPY pinot-distribution/target/apache-pinot-${PINOT_VERSION}-bin/apache-pinot-${PINOT_VERSION}-bin ${PINOT_HOME}

COPY docker/images/pinot/bin ${PINOT_HOME}/bin
COPY docker/images/pinot/etc ${PINOT_HOME}/etc
COPY docker/images/pinot/examples ${PINOT_HOME}/examples

RUN mkdir -p ${PINOT_HOME}/configs && \
    mkdir -p ${PINOT_HOME}/data && \
    chmod +x ${PINOT_HOME}/bin/*.sh

WORKDIR ${PINOT_HOME}
ENTRYPOINT ["./bin/pinot-admin.sh"]

CMD ["run"]
